### ISSUE TITLE
UI bug when trying to reach Spark marketplace page

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/spark-wallet-wrapper#10]
![image](https://user-images.githubusercontent.com/39687477/144675017-47cb981e-1393-4bb9-8e24-36558e603e4a.png)

Reported by: @kn0wmad

**Comment by ProofOfKeags** [comment]
Is this just spark? or any/all services? Might be a registry regression.

**Comment by elvece** [comment]
Just spark. It was not triggered to load the dependencies into the database. This is now fixed.

I did a regression on all other packages - they could all successfully be visited in the marketplace and installed.
