### ISSUE TITLE
Add Accesss Key to Properties

### ISSUE THREAD

**Issue by MattDHill** [Start9Labs/spark-wallet-wrapper#15]
When pairing with an Android device, the user must input their access key. This is currently only available by inspecting the "Pairing URL" property and extracting from the final query param. Better to have it's own field.

**Comment by kn0wmad** [comment]
@gStart9 is taking over this service.  Happy to help you get familiarized with packaging when you are ready

**Comment by gStart9** [comment]
Fixed up in #17
